ID_ESTADO_EMPLEADO = 3
ID_AREA_EMPLEADO = 4
ID_CARGO_EMPLEADO = 5

ID_ESTADO_FUNCIONARIO = 8
ID_AREA_FUNCIONARIO = 9
ID_CARGO_FUNCIONARIO= 10

ID_PORCENTAJE= 15
ID_MONEDA= 19

ID_TIPO_DOCUMENTO_FACTURA = 360 
ID_TIPO_DOCUMENTO_BOLETA = 361 